### ISSUE TITLE
" issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by hayase126** [hayase126/refresh#25]
### 概要
- MVPリリースまでの実装予定の内容です。

### 実装内容予定の機能
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] ログアウト機能
- [ ] 新規投稿機能
- [ ] 投稿一覧機能
- [ ] 投稿詳細機能
- [ ] 投稿削除機能
- [ ] コメント機能
- [ ] コメント削除機能
- [ ] いいね機能
- [ ] いいね削除機能
- [ ] マイページ
- [ ] マイページ編集
- [ ] 画像加工・合成（MiniMagick）

### 必要なページ
- [ ] topページ
- [ ] 新規登録ページ
- [ ] ログインページ
- [ ] 投稿一覧ページ（未ログインでも閲覧可能）
- [ ] 投稿詳細ページ（未ログインでも閲覧可能）
- [ ] ログイン前、ログイン後のヘッダー
- [ ] フッター
- [ ] マイページページ
- [ ] マイページ編集ページ
- [ ] いいね欄ページ
- [ ] 新規投稿ページ

**Comment by Tsuchiya2** [comment]
ご提出ありがとうございます。
ストーリーポイントが4のものがありますね。カリキュラムではフィボナッチ数列でストーリーポイントを付ける説明が書かれていたかと思うのでご確認と対応をお願いいたします。（3以上と感じるようでしたら、issueを分解して3以下になるようにしましょう）

**Comment by hayase126** [comment]
改めてよろしくお願いします！
