### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by hayase126** [hayase126/refresh#63]
## 各種情報
サービス名：りふれっ酒
サービスURL：https://refresh-7bog.onrender.com

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] ユーザー登録機能
- [x] ログイン機能
- [x] ログアウト機能
- [x] 新規投稿機能
- [x] 投稿一覧機能
- [x] 投稿詳細機能
- [x] 投稿削除機能
- [x] コメント機能
- [x] コメント削除機能
- [x] いいね機能
- [x] いいね削除機能
- [x] マイページ
- [x] マイページ編集
- [x] 画像加工・合成（MiniMagick）

### 必要なページ
- [x] topページ
[![Image from Gyazo](https://i.gyazo.com/e626b804b9b64459d39818da1c2c694d.png)](https://gyazo.com/e626b804b9b64459d39818da1c2c694d)
- [x] 新規登録ページ
[![Image from Gyazo](https://i.gyazo.com/ed6d1b42f1dc4a32281489cf1f790bbc.png)](https://gyazo.com/ed6d1b42f1dc4a32281489cf1f790bbc)
- [x] ログインページ
[![Image from Gyazo](https://i.gyazo.com/4dec90fc86815761d6affbc5bb764e60.png)](https://gyazo.com/4dec90fc86815761d6affbc5bb764e60)
- [x] 投稿一覧ページ（未ログインでも閲覧可能）
[![Image from Gyazo](https://i.gyazo.com/e74fbc84b4ef9020d48917ec25c2eab1.png)](https://gyazo.com/e74fbc84b4ef9020d48917ec25c2eab1)
- [x] 投稿詳細ページ（未ログインでも閲覧可能）
[![Image from Gyazo](https://i.gyazo.com/7603f61d681fa929ec2f5bdf2eb8a8b8.png)](https://gyazo.com/7603f61d681fa929ec2f5bdf2eb8a8b8)
- [x] マイページページ、いいね欄
[![Image from Gyazo](https://i.gyazo.com/08c9a9cce07c87618ccf925d146b596d.png)](https://gyazo.com/08c9a9cce07c87618ccf925d146b596d)
- [x] マイページ編集ページ
[![Image from Gyazo](https://i.gyazo.com/40c9ff3a14973c3f2bdcb764bf1e4d31.png)](https://gyazo.com/40c9ff3a14973c3f2bdcb764bf1e4d31)
- [x] 新規投稿ページ
[![Image from Gyazo](https://i.gyazo.com/a1a3c2e1806075623db1dfa2f9eb4b88.png)](https://gyazo.com/a1a3c2e1806075623db1dfa2f9eb4b88)

**Comment by ippei-shimizu** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
