### ISSUE TITLE
オートコンプリートについての質問

### ISSUE THREAD

**Issue by hayase126** [hayase126/refresh#82]
## 解決したいこと・達成したいものについて
オートコンプリート機能を実装中で、検索する時にStarted GET "/posts?q%5BになってしまうのをStarted GET "/postssearch?query=line"のようにしたいです

## 聞きたいこと・アドバイスが欲しいこと
ルーティングやapp/views/posts/search_form.html.erb、postsコントローラを確認してみるが原因がわからないのでアドバイスが欲しいです。

## 実装の際に参考にした資料等
https://qiita.com/Yamamoto-Masaya1122/items/879d6eb540ce4e05cfe5#5%E7%AB%A0stimulus-autocomplete%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB
基本資料通りに実行しました。

## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
(https://github.com/hayase126/refresh/pull/81)

## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
オートコンプリート機能で検索しようとした時にDBから表示されないのでviewsが間違えている？それともStarted GET "/posts?q%5B〜になっているのでルーティングが間違えている？と考えています。

## 検証した結果から分かったこと・考えたこと
ネットワークタブを見た時に、送信されるURL（リクエストURL）が/posts/searchとなっていないのでおそらくルーティングだと思っています。

よろしくお願いします。

**Comment by kenchasonakai** [comment]
> オートコンプリート機能を実装中で、検索する時にStarted GET "/posts?q%5BになってしまうのをStarted GET "/postssearch?query=line"のようにしたいです

検索するときというのはどのときでしょうか？
検索ボタンを押したとき、検索フォームに文字を入力したときなど、どのようなときなのかを切り分けてください
また、オートコンプリートを用いない検索機能は出来ていて、オートコンプリート機能のみ実装出来ないということであっていますか？


`gem "importmap-rails"`を追加していると思いますが、そもそもesbuildを使用しているのでimportmapを使用しないようにしましょう
importmap、esbuildについてわかっていなければRailsガイドの該当箇所を参照したり、いろいろ調べて理解しておくとよいかと思います。

また、`app/javascript/application.js`から`import "./controllers"`を削除しているのでstimulusが読み込まれない状態になっているかと思います。
stimulusについて理解していないのであれば理解できるように調べておきましょう

**Comment by hayase126** [comment]
importmap、esbuildについて調べてみたら知識不足でした！
調べた上でもう一度チャレンジしてみます！

ありがとうございます。
